250 replace addpartforminputs with mui
OptiCorp/inventory-app pull request #292
Opened 2024-02-02 14:34 UTC by Kodehodekatty

## Pull Request Summary

### What is missing from the codebase?

Currently, we're using own styled input fields and selects in the add part components present in the add part page. To follow code structure we're using Mui Textfield component and Autocomplete component. 

### Changes made in this pull request:

- replaced inputs/selects with Mui's components. cleaned up in structure, fixed styling to fit overall design, removed old styling files or unused styles. 
- fixed type changes /removed old types/ removed "name" in template type
- updated zod validation based on types/ removed "template name" from validation
- removed template name input field
- added media query to finish button in add part page for phone screen.
- configured eslint file to ignore prettier end of line error that causes problems for Windows.

## Checklist

-   [x] **Review**: Have you reviewed your own changes to ensure they align with best practices?

2024-02-02 14:57 UTC, Benjamin-Lyon requested changes

2024-02-02 14:57 UTC, Benjamin-Lyon commented on .editorconfig
is this still needed if we are just going to ignore the endOfLine prettier rule instead?

2024-02-02 14:57 UTC, Benjamin-Lyon commented on src/components/AddPartFormFields/Type/Type.tsx
> +            {' '}
We don't want these `{' '}` spaces

2024-02-02 14:57 UTC, Benjamin-Lyon commented on src/components/AddPartFormFields/styles.ts
> +    display: grid;
can we use [flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) to style here instead?

2024-02-02 14:57 UTC, Benjamin-Lyon commented on src/pages/addPart/styles.ts
> +    @media screen and (max-width: 800px) {
i like the use of media query here :)

2024-02-02 14:59 UTC, Benjamin-Lyon requested changes
see previous comments

2024-02-05 10:01 UTC, Benjamin-Lyon requested changes

2024-02-05 10:32 UTC, Kodehodekatty commented on src/components/AddItemFormFields/Type/Type.tsx
changed it to TemplateTypes

2024-02-05 11:39 UTC, Benjamin-Lyon requested changes

2024-02-05 11:39 UTC, Benjamin-Lyon commented on src/pages/addItem/Index.tsx
> +                    <Button
can we replace this button with the MUI button?

2024-02-05 12:37 UTC, Benjamin-Lyon approved these changes

2024-02-05 12:37 UTC, merged